### ISSUE TITLE
Controls unusable when MT-32 Pi attached

### ISSUE THREAD

**Issue by ajgowans** [MiSTer-devel/Arcade-Arkanoid_MISTer#14]
If an MT-32 Pi is attached to the iO board then the controls in game are unusable, you are dragged around in different directions and it glitches out.  Disconnecting the MT-32 Pi fixes this issue.  I was using an 8bitdo SN30pro (USB connected) and a Digital iO board.

Raising for visibility, as others may come across this issue and not know to disconnect their MT-32 pi, however it would be good if this could be fixed.

**Comment by sorgelig** [comment]
because this core supports spinner on USER_IO.
Probably disable option should be added

**Comment by sorgelig** [comment]
Added option to disable SNAC spinner.
